"use client";

import { useRef } from "react";
import { Printer, Download, X } from "lucide-react";
import { Button } from "@/components/ui/button";

interface Credential {
  username: string;
  password: string;
  displayName: string;
  email: string;
}

interface TeacherCredentialsSheetProps {
  students: Credential[];
  onClose: () => void;
  organizationName?: string;
}

export function TeacherCredentialsSheet({
  students,
  onClose,
  organizationName = "Math for Business Operations",
}: TeacherCredentialsSheetProps) {
  const printRef = useRef<HTMLDivElement>(null);

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-[60] flex flex-col bg-background overflow-hidden animate-in fade-in duration-200">
      <header className="flex items-center justify-between border-b px-6 py-4 bg-background print:hidden">
        <div>
          <h2 className="text-xl font-semibold">Student Credentials Sheet</h2>
          <p className="text-sm text-muted-foreground">Print or download these for your students.</p>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="outline" size="sm" className="gap-2" onClick={handlePrint}>
            <Printer className="size-4" />
            Print
          </Button>
          <Button variant="ghost" size="icon" onClick={onClose}>
            <X className="size-4" />
            <span className="sr-only">Close</span>
          </Button>
        </div>
      </header>

      <main className="flex-1 overflow-y-auto bg-muted/20 p-8 print:p-0 print:bg-white print:overflow-visible">
        <div 
          ref={printRef}
          className="mx-auto max-w-[8.5in] bg-white p-[0.5in] shadow-sm print:shadow-none print:p-0"
          style={{ minHeight: "11in" }}
        >
          <div className="mb-8 border-b-2 border-primary pb-4">
            <h1 className="text-2xl font-bold text-primary">{organizationName}</h1>
            <p className="text-sm text-muted-foreground">Student Login Credentials &mdash; {new Date().toLocaleDateString()}</p>
          </div>

          <div className="grid grid-cols-2 gap-4 print:grid-cols-2">
            {students.map((student, index) => (
              <div 
                key={index}
                className="border-2 border-dashed border-muted-foreground/30 p-4 rounded-lg space-y-3 break-inside-avoid"
              >
                <div className="flex justify-between items-start border-b pb-2">
                  <div className="font-bold text-lg">{student.displayName}</div>
                  <div className="text-[10px] uppercase tracking-wider text-muted-foreground font-semibold">Student Card</div>
                </div>
                
                <div className="grid grid-cols-3 gap-2 text-xs">
                  <div className="text-muted-foreground font-medium">URL:</div>
                  <div className="col-span-2 font-mono truncate text-primary">{window.location.origin}</div>
                  
                  <div className="text-muted-foreground font-medium">Username:</div>
                  <div className="col-span-2 font-mono font-bold">{student.username}</div>
                  
                  <div className="text-muted-foreground font-medium">Password:</div>
                  <div className="col-span-2 font-mono font-bold bg-muted/50 px-1 rounded">{student.password}</div>
                </div>

                <div className="pt-2 text-[9px] text-muted-foreground italic leading-tight">
                  Keep this card safe. Do not share your password with others.
                </div>
              </div>
            ))}
          </div>

          <footer className="mt-12 text-center text-[10px] text-muted-foreground border-t pt-4">
            Generated by Math for Business Operations v2 &bull; {new Date().toISOString()}
          </footer>
        </div>
      </main>

      <style jsx global>{`
        @media print {
          body * {
            visibility: hidden;
          }
          .print-area, .print-area * {
            visibility: visible;
          }
          main, main * {
            visibility: visible;
          }
          header {
            display: none !important;
          }
          @page {
            size: auto;
            margin: 0.5in;
          }
        }
      `}</style>
    </div>
  );
}
